name: Race-Updater-1

on:
  workflow_dispatch:  # Permet de lancer manuellement depuis l'interface GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: pip install requests beautifulsoup4

    - name: Exécuter le script
      run: python Race-Scrapper-1.py

    - name: Configurer les identifiants Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Commit du fichier JSON mis à jour
      run: 
