name: Mise à jour manuelle des courses GT7

on:
  workflow_dispatch:  # Permet de lancer manuellement depuis l'interface GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: pip install requests beautifulsoup4

    - name: Exécuter le script
      run: python scrape.py

    - name: Commit du fichier JSON mis à jour
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add courses.json
        git commit -m "Mise à jour manuelle des courses GT7"
        git push
